config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks do
    resource :subtasks
  end

  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
    belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :subtasks
    validates :title, :description, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
    before_action :set_task

    def new
        @subtask = @task.subtasks.new
    end

    def create
        @subtask = @task.subtasks.new(subtask_params)
        if @subtask.save
            redirect_to task_path(@task)
        else
            render :new, status: :unprocessable_entity
        end
    end
    private

    def set_task 
        @task = Task.find(params[:task_id])
    end
    def subtask_params
        params.require(:subtask).permit(:user_story, :story_points, :status, :task_id)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task , only: [:show, :edit, :update, :destroy] #step 1


    def index
        @tasks = Task.all
        @test = "This is a Test"
    end
    
    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to task_path(@task)

        else
            render :new, status: :unprocessable_entity
        end
       
    end

    def show
    end

    def edit #step 3
    end

    def update
       if @task.update(task_params)
        redirect_to task_path(@task)
       else
        render :edit, status: :unprocessable_entity
       end
    end

    def destroy
        if @task.destroy
            redirect_to tasks_path
        else
            "GG"
        end
    end

    private

    def set_task #step 2
        @task = Task.find(params[:id])
    end


    def task_params
        params.required(:task).permit(:title, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subtasks/_form.html.erb
<h1>New Subtask</h1>
<%= simple_form_for [@task, @subtask] do |f| %>
  <%= f.input :User_Story %>
  <%= f.input :Story_Point %>
  <%= f.input :Status %>
  <%= f.button :submit %>
<% end %>

app/views/subtasks/new.html.erb
<h1>New Subtask</h1>
<%= simple_form_for [@task, @subtask] do |f| %>
  <%= f.input :user_story %>
  <%= f.input :story_points, as: :float %>
  <%= f.input :status, collection: ["Pending", "In Development", "Completed"] %>
  <%= f.button :submit %>
<% end %>

app/views/subtasks/show.html.erb
<h1> This is the Subtask Show Page </h1>
<h3><%= @subtask.User Story %></h3>
<h4><%= @subtask.Story Points %></h4>
<h4><%= @subtask.Status %></h4>
<p>
<%= link_to 'Add subtask', new_subtask_path %>
</p>
<p>
<%= link_to "Subtask Index Page", subtasks_path %>
<p>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Page</h1>
<%= render partial: 'tasks/form' %>

app/views/tasks/index.html.erb
<h1>Hello Word</h1>
testing
<%= @test %>

<%= link_to 'Click here to create new task', new_task_path %>

<table>
    <thead>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
        <hr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
            <tr>
                <th><%= task.id %></th>
                <th><%= link_to task.title, task_path(task) %></th>
                <th><%= task.description %></th>
                <th><%= link_to "edit - #{task.id}", edit_task_path(task) %></th>
                <th><%= link_to 'delete', task_path(task), method: :delete %></th>
            </tr>
        <% end %>
    </tbody>
</table>
Total record: <%= @tasks.count %>

    

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render partial: 'tasks/form' %>

app/views/tasks/show.html.erb
<h1> This is the Show Page </h1>
<h3><%= @task.title %></h3>
<h4><%= @task.description %></h4>
<p>
<%= link_to 'Add subtask', new_task_subtasks_path(@task) %>
</p>
<p>
<%= link_to "Index Page", tasks_path %>
<p>

<table>
    <thead>
        <th>#</th>
        <th>User Story</th>
        <th>Story Points</th>
        <th>Status</th>
    <thead>
    <tbody>
    <% @task.subtasks.each do |task| %>
        <tr>
            <td><%= task.id %></td>
            <td><%= task.user_story %></td>
            <td><%= task.story_points %></td>
            <td><%= task.status %></td>
        </tr>
    <% end %>
    </tbody>
</table>